import cv2
import csv
import ast
import numpy as np

def export_contour_image(csv_path, image_path):
    """
    Export a high quality PNG image with contour overlays.
    
    This function reads the CSV file (generated by export_mask_coordinates) to obtain 
    the contour coordinates for each polygon (for rows of type "new_mask" or "mask"), 
    overlays the contours on the original image with a one-pixel width line, and saves 
    the result as a PNG image.
    
    Args:
        csv_path (str): Path to the CSV file containing contour coordinates.
        image_path (str): Path to the original image.
        
    Returns:
        output_png_path (str): The path to the saved PNG image.
    """
    # Load the original image.
    image = cv2.imread(image_path)
    if image is None:
        print(f"Error: Could not load image at {image_path}")
        return None

    import os
    base_name = os.path.splitext(os.path.basename(image_path))[0]
    file_directory = f"{os.path.splitext(image_path)[0]}_files"
    if not os.path.exists(file_directory):
        os.makedirs(file_directory)
    output_png_path = os.path.join(file_directory, f"{base_name}_final_drawing.png")

    # Open the CSV file and iterate over its rows.
    with open(csv_path, mode='r', newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            # Process only rows corresponding to masks.
            if row["type"] in ["new_mask", "mask"]:
                try:
                    # Convert the string representation back to a list of contours.
                    contours = ast.literal_eval(row["contour_coordinates"])
                except Exception as e:
                    print(f"Error parsing contour coordinates: {e}")
                    continue
                # Draw each contour.
                for contour in contours:
                    # Convert list of points to a NumPy array with shape (-1, 1, 2).
                    pts = np.array(contour, dtype=np.int32).reshape((-1, 1, 2))
                    # Draw the contour with one-pixel wide line; using red in BGR.
                    cv2.polylines(image, [pts], isClosed=True, color=(0, 0, 255), thickness=1)

    # Save the overlaid image as a PNG with minimal compression for high quality.
    success = cv2.imwrite(output_png_path, image, [cv2.IMWRITE_PNG_COMPRESSION, 0])
    if success:
        print(f"Exported image with contours to {output_png_path}")
        return output_png_path
    else:
        print("Error: Failed to save the output image.")
        return None
    

import os
import math
from PIL import Image, ImageDraw, ImageFont

def create_composite_image(folder_before: str, folder_after: str, output_filename: str = "composite.jpg", max_rows: int = 8) -> None:
    """
    Creates a composite JPEG image arranging matching PNG images from two folders side by side.
    
    The function will:
      1. Iterate through the two folders and find PNG images.
      2. Identify matching images (by filename) in both folders.
      3. Arrange the pairs in two columns (before on the left, after on the right) and in rows.
      4. Limit each table to `max_rows` rows. If there are more than max_rows pairs, additional tables are placed adjacent to the right.
      
    Parameters:
      folder_before (str): Path to the folder containing the "before" images.
      folder_after (str): Path to the folder containing the "after" images.
      output_filename (str): Filename for the output composite image (default "composite.jpg").
      max_rows (int): Maximum number of rows per table (default is 8).
    """
    
    # List PNG files (case-insensitive) in each folder
    files_before = [f for f in os.listdir(folder_before) if f.lower().endswith(".png")]
    files_after = [f for f in os.listdir(folder_after) if f.lower().endswith(".png")]
    
    # Find matching filenames
    matching_files = sorted(set(files_before).intersection(set(files_after)))
    
    if not matching_files:
        print("No matching PNG images found in the two folders.")
        return
    
    # Load matching image pairs
    pairs = []
    for filename in matching_files:
        path1 = os.path.join(folder_before, filename)
        path2 = os.path.join(folder_after, filename)
        try:
            img_before = Image.open(path1)
            img_after  = Image.open(path2)
            pairs.append((img_before, img_after))
        except Exception as e:
            print(f"Error loading images for {filename}: {e}")
    
    if not pairs:
        print("No images loaded successfully.")
        return

    # Assume all images have the same dimensions. Adjust or resize if needed.
    img_width, img_height = pairs[0][0].size
    # Set a font size relative to the image width (approximately 1/10th of the width)
    font_size = max(12, img_width // 2)
    try:
        font = ImageFont.truetype("arial.ttf", font_size)
    except IOError:
        try:
            font = ImageFont.truetype("DejaVuSans-Bold.ttf", font_size)
        except IOError:
            print("Warning: Could not load a scalable TTF font. Using default font which may not scale properly.")
            font = ImageFont.load_default()
    label_height = font_size + 10  # label row height is slightly larger than the font size
    
    # Determine the number of tables (columns) needed
    num_pairs = len(pairs)
    num_tables = math.ceil(num_pairs / max_rows)
    
    # Calculate composite image dimensions
    composite_width = num_tables * 2 * img_width  # 2 columns per table
    composite_height = label_height + max_rows * img_height
    
    # Create a blank composite image with a white background
    composite = Image.new("RGB", (composite_width, composite_height), color=(255, 255, 255))
    draw = ImageDraw.Draw(composite)
    for table_index in range(num_tables):
        # Calculate center positions for labels in each table column
        x_before_center = table_index * (2 * img_width) + img_width // 2
        x_after_center = table_index * (2 * img_width) + img_width + img_width // 2
        text_before = "before manual targeting"
        text_after = "after manual targeting"
        bbox_before = font.getbbox(text_before)
        text_before_width = bbox_before[2] - bbox_before[0]
        text_before_height = bbox_before[3] - bbox_before[1]
        bbox_after = font.getbbox(text_after)
        text_after_width = bbox_after[2] - bbox_after[0]
        text_after_height = bbox_after[3] - bbox_after[1]
        x_before_text = x_before_center - text_before_width // 2
        x_after_text = x_after_center - text_after_width // 2
        y_text = (label_height - text_before_height) // 2
        draw.text((x_before_text, y_text), text_before, fill=(0, 0, 0), font=font)
        draw.text((x_after_text, y_text), text_after, fill=(0, 0, 0), font=font)
    
    # Paste each pair into the composite image
    for idx, (img_before, img_after) in enumerate(pairs):
        table_index = idx // max_rows
        row_index = idx % max_rows
        
        # Calculate x positions for the "before" and "after" images
        x_before = table_index * (2 * img_width)
        x_after = x_before + img_width
        y = label_height + row_index * img_height
        
        composite.paste(img_before, (x_before, y))
        composite.paste(img_after, (x_after, y))
    
    # Save the composite image
    composite.save(output_filename)
    print(f"Composite image saved as {output_filename}")

import pickle
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
from section_identification.filtering import filtering

def plot_mask_area_histogram(
    mask_pkl_path: str,
    eps_values: np.ndarray = None,
    min_samples_values: range = None,
    bins: int = 30
) -> None:
    """
    Load masks from a pickle file, find the best DBSCAN params via your filtering()
    function, re-cluster all mask areas with those params, and plot a stacked histogram
    of area distributions colored by cluster label.

    Parameters
    ----------
    mask_pkl_path : str
        Path to the .pkl file containing the list of masks (each with mask['area']).
    eps_values : array-like, optional
        Grid of eps values to try in filtering(); defaults to np.linspace(100,1200,11).
    min_samples_values : iterable of int, optional
        Grid of min_samples values to try in filtering(); defaults to range(1,5).
    bins : int, optional
        Number of histogram bins.
    """
    # 1. Load masks
    with open(mask_pkl_path, 'rb') as f:
        masks = pickle.load(f)

    # 2. Set up parameter grids if none provided
    if eps_values is None:
        eps_values = np.linspace(100, 1200, 11)
    if min_samples_values is None:
        min_samples_values = range(1, 5)

    # 3. Run your filtering() to pick the “best” (eps, min_samples)
    _, (eps_chosen, min_samples_chosen) = filtering(masks, eps_values, min_samples_values)

    # 4. Extract all mask areas
    areas = np.array([m['area'] for m in masks])

    # 5. Re-cluster with chosen params so every mask gets a label
    db = DBSCAN(eps=eps_chosen, min_samples=min_samples_chosen)
    labels = db.fit_predict(areas.reshape(-1, 1))

    # 6. Identify the largest non-noise cluster
    unique_labels = np.unique(labels)
    cluster_sizes = {lab: np.sum(labels == lab) for lab in unique_labels if lab != -1}
    if cluster_sizes:
        largest_label = max(cluster_sizes, key=cluster_sizes.get)
    else:
        largest_label = -1

    # Prepare indices and areas
    all_ids = np.arange(len(areas))
    all_areas = areas
    mask_idx = labels == largest_label
    mask_ids = all_ids[mask_idx]
    cluster_areas = areas[mask_idx]

    # 7. Plot all masks with main cluster highlighted on log scale
    plt.figure(figsize=(10, 6))
    plt.scatter(all_ids, all_areas, s=10, alpha=0.3, color='gray', label='Other masks')
    plt.scatter(mask_ids, cluster_areas, s=20, alpha=0.7, color='C0', label=f'Cluster {largest_label}')
    plt.yscale('log')
    plt.xlabel('Mask ID')
    plt.ylabel('Area (pixels, log scale)')
    plt.title(
        f'All masks by area with main cluster highlighted '
        f'(eps={eps_chosen:.1f}, min_samples={min_samples_chosen})'
    )
    plt.legend(loc='upper left')
    plt.tight_layout()
    plt.show()